"""Use azure storage

Revision ID: 6748a9d541e5
Revises: 2a2965c24a34
Create Date: 2024-12-16 10:08:11.266436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6748a9d541e5"
down_revision: Union[str, None] = "2a2965c24a34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column(
        "scans", sa.Column("blob_name", sa.String(length=255), nullable=True)
    )

    # Update existing rows with a default value (using the id as a unique identifier)
    op.execute(
        "UPDATE scans SET blob_name = 'scan_' || id::text WHERE blob_name IS NULL"
    )

    # Now make it non-nullable
    op.alter_column("scans", "blob_name", nullable=False)

    op.alter_column(
        "scans",
        "error_message",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scans",
        "error_message",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("scans", "blob_name")
    # ### end Alembic commands ###
